# Generated by TKproE 2.30 - Wed Feb 23 11:33:47 MSK 2022

proc TPinitImages {} {
# Load all images


}

# Define named fonts

# Global variable initialization
proc TPinitVars {} {
# Initialize global variables
namespace eval :: {;#Creating namespace ::;}

set ::TPexclusions(user_namespace) {}
set ::TPprojType TCL_TK
set ::TPsaveValues 1
array set ::TPbuild {Win64 0 compression 0 MacOS 0 Win32 0 ICOfile /home/a513/ORLOV/TK_Tcl/Project/FREEWRAP/PKCS_CA_KDE/icon_p7_48x48.png MainSrc /home/a513/ORLOV/TK_Tcl/Project/FREEWRAP/TKProE/SOURCE_230/EXAMPLES/test_smooth_4_Full.tcl Exec_Linux64 /usr/local/bin64/tclexecomp64 result {} IncludeFiles {} wrapper 1 Exec_Linux32 {} appName test_smooth_4_Full_tclexecomp_bin buildType buildEXE Linux64 1 IncludeDir {} Exec_Win64 /home/a513/ORLOV/TK_Tcl/Project/FREEWRAP/TCLEXECOMP/tclexecomp-V1.2.0/tclexecomp64.exe Linux32 0 destDir /tmp Exec_Win32 {} firstTime 0 Exec_MacOS /home/a513/ORLOV/TK_Tcl/Project/FREEWRAP/TCLEXECOMP/CUSTOM/tclexecomp64.mac}
}

# Toplevel window procedures
proc TPopenWindow. {} {
# CLONEPATH = .
# Cloned Wed Feb 23 11:33:47 MSK 2022



. configure  -background {#e0dfde}

bindtags . {. Tkproe.tcl all}
wm title . tkproe.tcl
wm aspect . 
wm focusmodel . passive
wm grid . 
wm geometry . 380x505+234+267
wm iconmask . 
wm iconposition . 
wm maxsize . 1585 870
wm minsize . 1 1
wm overrideredirect . 0
wm positionfrom . user
wm resizable . 1 1
wm sizefrom . 
wm state . normal
wm transient . 
wm protocol . WM_DELETE_WINDOW { exit 0}


button .button0 -activebackground {#e0dfde} -activeforeground {#141312} -background {#e0dfde} -command {puts "Command XAXA"} -foreground {#141312} -highlightbackground {#e0dfde} -highlightcolor {#141312} -text {button0}

bindtags .button0 {. .button0 Button all}
pack .button0 -anchor center -expand 0 -fill none -ipadx 0 -ipady 0 -padx 0 -pady 0 -side top


button .canbutton1 -activebackground {#e0dfde} -activeforeground {#141312} -background {#e0dfde} -foreground {#141312} -highlightbackground {#e0dfde} -highlightcolor {#141312} -text {button1}

bindtags .canbutton1 {. .canbutton1 Button all}


canvas .canvas2 -background {#FAF0E6} -height {265} -highlightbackground {#ffffff} -highlightcolor {#141312} -width {378}

bindtags .canvas2 {. .canvas2 Canvas DrawTools all}
bind .canvas2 <Button-3> {puts "Я на холсте"}

set TPtemp [.canvas2 create polygon 56.0 94.1653170322258 76.0 94.1653170322258 113.0 94.1653170322258 133.0 94.1653170322258 133.0 121.80830306086472 133.0 145.30484118520786 133.0 172.9478272138466 113.0 172.9478272138466 76.0 172.9478272138466 56.0 172.9478272138466 56.0 145.30484118520786 56.0 121.80830306086472 -activewidth 0.0 -dashoffset 0 -disabledwidth 0.0 -fill #FFDEAD -joinstyle round -offset 0,0 -outline #458B00 -outlineoffset 0,0 -smooth true -splinesteps 12 -tags butexit -width 3.0]
set TPtemp [.canvas2 create rectangle 235.32869822485208 132.61997645315495 308.37455621301774 196.38002354684505 -activewidth 0.0 -dashoffset 0 -disabledwidth 0 -fill #8B2323 -offset 0,0 -outline #000000 -outlineoffset 0,0 -tags butexit -width 4.0]
.canvas2 bind $TPtemp <ButtonRelease-1> {puts "Я здесь"
}
set TPtemp [.canvas2 create text 66.0986093266287 65.33242078052393 -anchor center -angle 0.0 -fill #000000 -font {arial 27} -justify left -offset 0,0 -text text -underline -1 -width 0]
set TPtemp [.canvas2 create rectangle 86.21621621621614 167.65957446808517 245.78378378378386 242.3404255319149 -activewidth 0.0 -dashoffset 0 -disabledwidth 0 -fill #228B22 -offset 0,0 -outline #000000 -outlineoffset 0,0 -stipple gray25 -width 4.0]
set TPtemp [.canvas2 create line 12.532497472816488 26.074794627801325 273.55225533150445 101.53406112760968 -activewidth 0.0 -arrow first -arrowshape {8 10 3} -capstyle butt -fill blue -dashoffset 0 -disabledwidth 0.0 -joinstyle round -offset 0,0 -smooth 0 -splinesteps 12 -width 4.0]
set TPtemp [.canvas2 create rectangle 134.0 5.0 334.0 95.0 -activewidth 0.0 -dashoffset 0 -disabledwidth 0 -fill #228B22 -offset 0,0 -outline #000000 -outlineoffset 0,0 -width 4.0]
pack .canvas2 -anchor center -expand 0 -fill none -ipadx 0 -ipady 0 -padx 0 -pady 0 -side top


set TPtemp [.canvas2 create window 57.0 207.0 -anchor center -height 0 -width 0 -window .canbutton1]
pack .canvas2 .button0 -in .}

proc TPcloseWindow. {} {
wm state . withdrawn}

# User created procedures
namespace eval :: {
#Creating namespace ::
}

# Display and start the application
TPinitImages
if {[info proc TPstartupSrc] != {}} { TPstartupSrc }
TPinitVars
TPopenWindow.
if {[info proc TPendSrc] != {}} { TPendSrc }

# End of TKproE generated code
